api:
  name: "tgif-mobilepos-papi"
  version: "v1"
  token: "![e4mc3+h1W0F8b4nmyNsT3Y3D0rFmQvSLp5fctqUTsQYQaYP0/iX+FGaeHkttVUxaHHUCQJO9IywXKtggwrjs2sb2++po9EN4epIOrcopziPu3WVl48zUx6zMJu+ZoanCKbD9qcoPmCUwEFYyIIZJvHrE1XOh9Doe9CiOb0usfCxIqECAD29QKFmi0hm3ZWwT4Mx/AkgM91LaJ5vHOWkM+z+sN+0wp5tjxrsRw2ENFmiSPz6rgB+naY/+XyWfPTDfXhvE55lnB7Xrtj1tbjm5O48r6dsx6IX8GXqPKYI0lSa1m0tFFCVrIxXt68lVa3S3ci8AArk6/153uxtwSkM09dx1KsmPE8mCIFHtHtUld3dI338LVjfiQM9eq80tO1z9SVwVBtAYp7R74OlthtQH7kXcxH7sV0hM6seJRms/C/g=]"  
  https:
    port: "8082"
    
keystore:
  password: "![gKufGgL7g9k=]"

untilsuccessful:
  retries: "2"
  interval: "30000"

microsApi:
  connectionTimeout: "15000"
  readTimeout: "30000"
database:
  driver: "com.microsoft.sqlserver.jdbc.SQLServerDriver"  
  muleInterface:
    user: "svc_MuleSoft_User"
    password: "![puCF7jxzkk69M3/W7b3Gpg==]"
    url: "jdbc:sqlserver://10.58.50.50:1433;databaseName=mulesoft_interface;"  
  depot:
    user: "svc_MobileApp_notify"
    password: "![3+F+WCVBMVWZ+KoOEXPAVQ==]"
    url: "jdbc:sqlserver://10.58.50.50:1433;databaseName=depot;"
  reconnect:
    frequency: "2000"
    count: "2"
posapi:
  reconnect:
    frequency: "2000"
    count: "3"
key: "December 9, 2015"
domain: "tgif-mobilepos-papi"
tgif:
  logger:
    database:
      host: "10.58.50.50"
      port: "1433"
      user: "svc_MuleSoft_User"
      password: "![puCF7jxzkk69M3/W7b3Gpg==]"
      dbName: "mulesoft_interface"
    
